#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SushEat.Droid.Resource", IsApplication=true)]

namespace SushEat.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::SushEat.Droid.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::SushEat.Droid.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::SushEat.Droid.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::SushEat.Droid.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::SushEat.Droid.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::SushEat.Droid.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::SushEat.Droid.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::SushEat.Droid.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::SushEat.Droid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::SushEat.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int row_background = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int row_pressed_end = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int row_pressed_start = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int row_selected = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int row_text2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int theme_devicedefault_background = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int welcomeMessageText1 = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackgroundImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_arrow_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int list_item_selector = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int PrivateUser = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int RestaurantChef = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int RestaurantCustomer = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int button1 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int button2 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int button3 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int button4 = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int gridLayout2 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int textView1 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int textView2 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int textView3 = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int webview = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int welcomeMessage = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int welcomeMessage1 = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int operateMachine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SushiMenu = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
