#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SushEat.Droid.Resource", IsApplication=true)]

namespace SushEat.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int row_background = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int row_pressed_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int row_pressed_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int row_selected = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int row_text2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int theme_devicedefault_background = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int welcomeMessageText1 = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackgroundImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int list_item_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menu = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int newveg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rolls = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sauce = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sushi = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int veg = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int PrivateUser = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int RestaurantChef = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int RestaurantCustomer = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int Rolls = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int Sauce = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int Veg = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int button1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int button2 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int button3 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button4 = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int gridLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int listView1 = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int textView2 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int textView3 = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int welcomeMessage = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int welcomeMessage1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int operateMachine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Rolls = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Sauce = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Veg = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
